<?php

namespace App\Support\Taxonomy;

final class TaxonomyCatalog
{
    /**
     * Raw source value -> canonical value.
     * Canonical value is English enum/name where possible.
     *
     * @var array<string, array<string, string>>
     */
    private const NORMALIZATION_MAPS = [
        'make' => [
            '현대' => 'Hyundai',
            '기아' => 'Kia',
            '제네시스' => 'Genesis',
            '쉐보레(GM대우)' => 'Chevrolet',
            '쉐보레' => 'Chevrolet',
            'GM대우' => 'Chevrolet',
            '한국GM' => 'Chevrolet',
            '르노코리아(삼성)' => 'Renault Korea',
            '르노코리아' => 'Renault Korea',
            '르노삼성' => 'Renault Samsung',
            '쌍용' => 'SsangYong',
            'KG모빌리티' => 'KG Mobility',
            '벤츠' => 'Mercedes-Benz',
            '메르세데스-벤츠' => 'Mercedes-Benz',
            '아우디' => 'Audi',
            '폭스바겐' => 'Volkswagen',
            '볼보' => 'Volvo',
            '랜드로버' => 'Land Rover',
            '재규어' => 'Jaguar',
            '포르쉐' => 'Porsche',
            '렉서스' => 'Lexus',
            '토요타' => 'Toyota',
            '도요타' => 'Toyota',
            '혼다' => 'Honda',
            '닛산' => 'Nissan',
            '인피니티' => 'Infiniti',
            '마쯔다' => 'Mazda',
            '마쓰다' => 'Mazda',
            '미쯔비시' => 'Mitsubishi',
            '미쓰비시' => 'Mitsubishi',
            '스바루' => 'Subaru',
            '테슬라' => 'Tesla',
            '포드' => 'Ford',
            '지프' => 'Jeep',
            '닷지' => 'Dodge',
            '링컨' => 'Lincoln',
            '푸조' => 'Peugeot',
            '대우' => 'Daewoo',
            '미니' => 'MINI',
            '페라리' => 'Ferrari',
            '람보르기니' => 'Lamborghini',
            '마세라티' => 'Maserati',
            '벤틀리' => 'Bentley',
            '롤스로이스' => 'Rolls-Royce',
            '로터스' => 'Lotus',
            '르노' => 'Renault',
            '맥라렌' => 'McLaren',
            '스마트' => 'Smart',
            '스즈키' => 'Suzuki',
            '시트로엥' => 'Citroen',
            '알파로메오' => 'Alfa Romeo',
            '애스턴마틴' => 'Aston Martin',
            '이베코' => 'Iveco',
            '인피니니' => 'Infiniti',
            '폭스홀' => 'Vauxhall',
            '피아트' => 'Fiat',
            'KG모빌리티(쌍용)' => 'KG Mobility',
            '캐딜락' => 'Cadillac',
            '시트로엥/DS' => 'Citroen',
            '폴스타' => 'Polestar',
            '크라이슬러' => 'Chrysler',
            '이네오스' => 'Ineos',
            '중한자동차' => 'ZhongHan',
            '동풍소콘' => 'Dongfeng',

            'hyundai' => 'Hyundai',
            'kia' => 'Kia',
            'genesis' => 'Genesis',
            'chevrolet' => 'Chevrolet',
            'renault korea' => 'Renault Korea',
            'renault samsung' => 'Renault Samsung',
            'ssangyong' => 'SsangYong',
            'kg mobility' => 'KG Mobility',
            'bmw' => 'BMW',
            'mercedes-benz' => 'Mercedes-Benz',
            'audi' => 'Audi',
            'volkswagen' => 'Volkswagen',
            'volvo' => 'Volvo',
            'land rover' => 'Land Rover',
            'jaguar' => 'Jaguar',
            'porsche' => 'Porsche',
            'lexus' => 'Lexus',
            'toyota' => 'Toyota',
            'honda' => 'Honda',
            'nissan' => 'Nissan',
            'infiniti' => 'Infiniti',
            'mazda' => 'Mazda',
            'mitsubishi' => 'Mitsubishi',
            'subaru' => 'Subaru',
            'tesla' => 'Tesla',
            'ford' => 'Ford',
            'jeep' => 'Jeep',
            'dodge' => 'Dodge',
            'lincoln' => 'Lincoln',
            'peugeot' => 'Peugeot',
            'daewoo' => 'Daewoo',
            'mini' => 'MINI',
            'ferrari' => 'Ferrari',
            'lamborghini' => 'Lamborghini',
            'maserati' => 'Maserati',
            'bentley' => 'Bentley',
            'rolls-royce' => 'Rolls-Royce',
            'lotus' => 'Lotus',
            'renault' => 'Renault',
            'mclaren' => 'McLaren',
            'smart' => 'Smart',
            'suzuki' => 'Suzuki',
            'citroen' => 'Citroen',
            'alfa romeo' => 'Alfa Romeo',
            'aston martin' => 'Aston Martin',
            'iveco' => 'Iveco',
            'vauxhall' => 'Vauxhall',
            'fiat' => 'Fiat',
            'cadillac' => 'Cadillac',
            'polestar' => 'Polestar',
            'chrysler' => 'Chrysler',
            'ineos' => 'Ineos',
            'ds' => 'DS',
            'gmc' => 'GMC',
            'byd' => 'BYD',
            'man' => 'MAN',
        ],

        'body_type' => [
            '세단' => 'sedan',
            '대형차' => 'sedan',
            '중형차' => 'sedan',
            '준중형차' => 'sedan',
            '소형차' => 'sedan',
            '대형' => 'sedan',
            '준대형' => 'sedan',
            '중형' => 'sedan',
            '소형' => 'sedan',
            '준중형' => 'sedan',
            'sedan' => 'sedan',

            'RV' => 'suv',
            'SUV' => 'suv',
            'suv' => 'suv',

            '해치백' => 'hatchback',
            'hatchback' => 'hatchback',

            '쿠페' => 'coupe',
            '스포츠카' => 'coupe',
            'coupe' => 'coupe',

            '컨버터블' => 'convertible',
            'convertible' => 'convertible',

            '왜건' => 'wagon',
            'wagon' => 'wagon',

            '밴' => 'van',
            'van' => 'van',
            'MPV' => 'van',

            '승합' => 'minivan',

            '트럭' => 'truck',
            'truck' => 'truck',

            '카고' => 'cargo',

            '경차' => 'kei',

            '픽업트럭' => 'pickup',
            '픽업' => 'pickup',
        ],

        'transmission' => [
            '오토' => 'automatic',
            '자동' => 'automatic',
            'auto' => 'automatic',
            'automatic' => 'automatic',

            '수동' => 'manual',
            'manual' => 'manual',

            'CVT' => 'cvt',
            'cvt' => 'cvt',

            'DCT' => 'dct',
            'dct' => 'dct',
            '자동(DCT)' => 'dct',
        ],

        'fuel' => [
            '가솔린' => 'gasoline',
            'petrol' => 'gasoline',
            'gasoline' => 'gasoline',

            '디젤' => 'diesel',
            'diesel' => 'diesel',

            'LPG' => 'lpg',
            'lpg' => 'lpg',

            'CNG' => 'cng',
            'cng' => 'cng',

            '전기' => 'electric',
            'electric' => 'electric',

            '하이브리드' => 'hybrid',
            '가솔린+전기' => 'hybrid',
            '디젤+전기' => 'hybrid',
            'LPG+전기' => 'hybrid',
            '가솔린 하이브리드' => 'hybrid',
            '디젤 하이브리드' => 'hybrid',
            'hybrid' => 'hybrid',
            'HEV' => 'hybrid',

            '플러그인 하이브리드' => 'plugin_hybrid',
            '가솔린+전기(플러그인)' => 'plugin_hybrid',
            'PHEV' => 'plugin_hybrid',
            'plugin_hybrid' => 'plugin_hybrid',

            '수소' => 'hydrogen',
            '수소전기' => 'hydrogen',
            '수소전기차' => 'hydrogen',
            '연료전지' => 'hydrogen',
            'FCEV' => 'hydrogen',
            'hydrogen' => 'hydrogen',
        ],

        'drive_type' => [
            '전륜' => 'fwd',
            '전륜구동' => 'fwd',
            'FF' => 'fwd',
            'FWD' => 'fwd',
            'fwd' => 'fwd',
            '2WD' => 'fwd',

            '후륜' => 'rwd',
            '후륜구동' => 'rwd',
            'FR' => 'rwd',
            'RWD' => 'rwd',
            'rwd' => 'rwd',
            'sDrive' => 'rwd',

            'AWD' => 'awd',
            'awd' => 'awd',
            '4WD' => 'awd',
            '4wd' => 'awd',
            '4륜' => 'awd',
            '4륜구동' => 'awd',
            '사륜' => 'awd',
            '사륜구동' => 'awd',
            '상시사륜' => 'awd',
            '풀타임사륜' => 'awd',
            '파트타임사륜' => 'awd',
            '4Matic' => 'awd',
            '4Matic+' => 'awd',
            'xDrive' => 'awd',
        ],
    ];

    /**
     * value(lowercase) -> label by locale and field.
     *
     * @var array<string, array<string, array<string, string>>>
     */
    private const LABELS = [
        'ru' => [
            'body_type' => [
                'sedan' => 'Седан',
                'suv' => 'SUV',
                'hatchback' => 'Хэтчбек',
                'coupe' => 'Купе',
                'convertible' => 'Кабриолет',
                'wagon' => 'Универсал',
                'van' => 'Фургон',
                'minivan' => 'Минивэн',
                'pickup' => 'Пикап',
                'truck' => 'Грузовой',
                'cargo' => 'Грузовой фургон',
                'kei' => 'Малолитражка',
            ],
            'transmission' => [
                'automatic' => 'Автомат',
                'manual' => 'Механика',
                'cvt' => 'Вариатор',
                'dct' => 'Робот (DCT)',
            ],
            'fuel' => [
                'gasoline' => 'Бензин',
                'diesel' => 'Дизель',
                'lpg' => 'LPG',
                'cng' => 'CNG',
                'electric' => 'Электро',
                'hybrid' => 'Гибрид',
                'plugin_hybrid' => 'Plug-in гибрид',
                'hydrogen' => 'Водород',
            ],
            'drive_type' => [
                'fwd' => 'Передний',
                'rwd' => 'Задний',
                'awd' => 'Полный',
                '4wd' => '4WD',
                '2wd' => '2WD',
            ],
            'color' => [
                'black' => 'Чёрный',
                'white' => 'Белый',
                'silver' => 'Серебристый',
                'gray' => 'Серый',
                'blue' => 'Синий',
                'red' => 'Красный',
                'green' => 'Зелёный',
                'brown' => 'Коричневый',
                'gold' => 'Золотой',
                'orange' => 'Оранжевый',
                'yellow' => 'Жёлтый',
                'purple' => 'Фиолетовый',
                'beige' => 'Бежевый',
                'two-tone' => 'Двухцветный',
                'white two-tone' => 'Двухцветный (белый)',
                'black two-tone' => 'Двухцветный (чёрный)',
                'silver two-tone' => 'Двухцветный (серебристый)',
                'pearl two-tone' => 'Двухцветный (перламутр)',
                'gold two-tone' => 'Двухцветный (золотой)',
                'brown two-tone' => 'Двухцветный (коричневый)',
                'ivory two-tone' => 'Двухцветный (слон. кость)',
                'pink' => 'Розовый',

                '검정색' => 'Чёрный',
                '검정' => 'Чёрный',
                '흰색' => 'Белый',
                '은색' => 'Серебристый',
                '회색' => 'Серый',
                '파란색' => 'Синий',
                '빨간색' => 'Красный',
                '녹색' => 'Зелёный',
                '갈색' => 'Коричневый',
                '금색' => 'Золотой',
                '주황색' => 'Оранжевый',
                '노란색' => 'Жёлтый',
                '보라색' => 'Фиолетовый',
                '베이지' => 'Бежевый',
                '투톤' => 'Двухцветный',

                '은회색' => 'Серебристый',
                '인기색상' => 'Разный',
                '파랑색' => 'Синий',
                '하늘색' => 'Синий',
                '담녹색' => 'Зелёный',
                '연금색' => 'Золотой',
                '명은색' => 'Серебристый',
                '연두색' => 'Зелёный',
                '은하색' => 'Серебристый',
                '자주색' => 'Фиолетовый',
                '갈대색' => 'Коричневый',
                '빨강색' => 'Красный',
                '청옥색' => 'Синий',
                '초록색' => 'Зелёный',
                '노랑색' => 'Жёлтый',
                '미색' => 'Белый',
                '흰색투톤' => 'Двухцветный',
                '검정투톤' => 'Двухцветный',
                '초록(연두)' => 'Зелёный',
                '노랑' => 'Жёлтый',
                '은색투톤' => 'Двухцветный',
                '분홍색' => 'Розовый',
                '진주투톤' => 'Двухцветный',
                '다크그레이' => 'Серый',
                '카본블랙' => 'Чёрный',
                '남색' => 'Синий',
                '진청색' => 'Синий',
                '진청' => 'Синий',
                '금색투톤' => 'Двухцветный',
                '베이지색' => 'Бежевый',
                '갈색투톤' => 'Двухцветный',
                '폴라 화이트' => 'Белый',
                '폴라화이트' => 'Белый',
                '아마존그레이' => 'Серый',
                '스노우화이트' => 'Белый',
                '스노우 화이트 펄' => 'Белый',
                '진회색' => 'Серый',
                '톰보이카키' => 'Зелёный',
                '아이보리색투톤' => 'Двухцветный',
                '소피스토그레이' => 'Серый',
                '알파인화이트' => 'Белый',
                '알파인 화이트' => 'Белый',
                '곤색' => 'Синий',
                '군청색' => 'Синий',
                '기타' => 'Другой',
                '슬릭실버' => 'Серебристый',
                '블랙사파이어' => 'Чёрный',
                '셀레나이트 그레이' => 'Серый',
                '셀레나이트그레이' => 'Серый',
                '세레니티화이트펄' => 'Белый',
                '세레니티 화이트 펄' => 'Белый',
                '자주(보라)' => 'Фиолетовый',
                '사이버그레이' => 'Серый',
                '사이버 그레이' => 'Серый',
                '옵시디안블랙' => 'Чёрный',
                '아틀라스 화이트' => 'Белый',
                '크리미화이트' => 'Белый',
                '초록' => 'Зелёный',
                '임페리얼블루' => 'Синий',
                '하이퍼메탈릭' => 'Серебристый',
                '하이퍼 매탈릭' => 'Серебристый',
                '플래티넘 실버' => 'Серебристый',
                '티타늄실버' => 'Серебристый',
                '순백색' => 'Белый',
                '화이트펄' => 'Белый',
                '그래비티 골드 매트' => 'Золотой',
                '밀키베이지' => 'Бежевый',
                '마그네틱포스' => 'Серый',
                '마그네틱 포스' => 'Серый',
                '녹턴그레이' => 'Серый',
                '녹턴 그레이 메탈릭' => 'Серый',
                '다크블루' => 'Синий',
                '문라이트 클라우드' => 'Белый',
                '문라이트클라우드' => 'Белый',
                '블루스톤' => 'Синий',
                '스카이스크래퍼그레이' => 'Серый',
                '드라빗그레이' => 'Серый',
                '글래시어 화이트' => 'Белый',
                '라군블루' => 'Синий',
                '타이푼실버' => 'Серебристый',
                '페퍼그레이' => 'Серый',
                '브라이트 실버' => 'Серебристый',
                '오션뷰' => 'Синий',
                '다크그래이색' => 'Серый',
                '아이언그레이' => 'Серый',
                '어비스블랙' => 'Чёрный',
                '미드나잇블랙' => 'Чёрный',
            ],
        ],

        'en' => [
            'body_type' => [
                'sedan' => 'Sedan',
                'suv' => 'SUV',
                'hatchback' => 'Hatchback',
                'coupe' => 'Coupe',
                'convertible' => 'Convertible',
                'wagon' => 'Wagon',
                'van' => 'Van',
                'minivan' => 'Minivan',
                'pickup' => 'Pickup',
                'truck' => 'Truck',
                'cargo' => 'Cargo Van',
                'kei' => 'Kei Car',
            ],
            'transmission' => [
                'automatic' => 'Automatic',
                'manual' => 'Manual',
                'cvt' => 'CVT',
                'dct' => 'DCT',
            ],
            'fuel' => [
                'gasoline' => 'Gasoline',
                'diesel' => 'Diesel',
                'lpg' => 'LPG',
                'cng' => 'CNG',
                'electric' => 'Electric',
                'hybrid' => 'Hybrid',
                'plugin_hybrid' => 'Plug-in Hybrid',
                'hydrogen' => 'Hydrogen',
            ],
            'drive_type' => [
                'fwd' => 'FWD',
                'rwd' => 'RWD',
                'awd' => 'AWD',
                '4wd' => '4WD',
                '2wd' => '2WD',
            ],
            'color' => [
                'black' => 'Black',
                'white' => 'White',
                'silver' => 'Silver',
                'gray' => 'Gray',
                'blue' => 'Blue',
                'red' => 'Red',
                'green' => 'Green',
                'brown' => 'Brown',
                'gold' => 'Gold',
                'orange' => 'Orange',
                'yellow' => 'Yellow',
                'purple' => 'Purple',
                'beige' => 'Beige',
                'two-tone' => 'Two-tone',
                'pink' => 'Pink',

                '은회색' => 'Silver',
                '인기색상' => 'Other',
                '파랑색' => 'Blue',
                '하늘색' => 'Blue',
                '담녹색' => 'Green',
                '연금색' => 'Gold',
                '명은색' => 'Silver',
                '연두색' => 'Green',
                '은하색' => 'Silver',
                '자주색' => 'Purple',
                '갈대색' => 'Brown',
                '빨강색' => 'Red',
                '청옥색' => 'Blue',
                '초록색' => 'Green',
                '노랑색' => 'Yellow',
                '미색' => 'White',
                '흰색투톤' => 'White Two-Tone',
                '검정투톤' => 'Black Two-Tone',
                '초록(연두)' => 'Green',
                '노랑' => 'Yellow',
                '은색투톤' => 'Silver Two-Tone',
                '분홍색' => 'Pink',
                '진주투톤' => 'Pearl Two-Tone',
                '다크그레이' => 'Gray',
                '카본블랙' => 'Black',
                '남색' => 'Blue',
                '진청색' => 'Blue',
                '진청' => 'Blue',
                '금색투톤' => 'Gold Two-Tone',
                '베이지색' => 'Beige',
                '갈색투톤' => 'Brown Two-Tone',
                '폴라 화이트' => 'White',
                '폴라화이트' => 'White',
                '아마존그레이' => 'Gray',
                '스노우화이트' => 'White',
                '스노우 화이트 펄' => 'White',
                '진회색' => 'Gray',
                '톰보이카키' => 'Green',
                '아이보리색투톤' => 'Ivory Two-Tone',
                '소피스토그레이' => 'Gray',
                '알파인화이트' => 'White',
                '알파인 화이트' => 'White',
                '곤색' => 'Blue',
                '군청색' => 'Blue',
                '기타' => 'Other',
                '슬릭실버' => 'Silver',
                '블랙사파이어' => 'Black',
                '셀레나이트 그레이' => 'Gray',
                '셀레나이트그레이' => 'Gray',
                '세레니티화이트펄' => 'White',
                '세레니티 화이트 펄' => 'White',
                '자주(보라)' => 'Purple',
                '사이버그레이' => 'Gray',
                '사이버 그레이' => 'Gray',
                '옵시디안블랙' => 'Black',
                '아틀라스 화이트' => 'White',
                '크리미화이트' => 'White',
                '초록' => 'Green',
                '임페리얼블루' => 'Blue',
                '하이퍼메탈릭' => 'Silver',
                '하이퍼 매탈릭' => 'Silver',
                '플래티넘 실버' => 'Silver',
                '티타늄실버' => 'Silver',
                '순백색' => 'White',
                '화이트펄' => 'White',
                '그래비티 골드 매트' => 'Gold',
                '밀키베이지' => 'Beige',
                '마그네틱포스' => 'Gray',
                '마그네틱 포스' => 'Gray',
                '녹턴그레이' => 'Gray',
                '녹턴 그레이 메탈릭' => 'Gray',
                '다크블루' => 'Blue',
                '문라이트 클라우드' => 'White',
                '문라이트클라우드' => 'White',
                '블루스톤' => 'Blue',
                '스카이스크래퍼그레이' => 'Gray',
                '드라빗그레이' => 'Gray',
                '글래시어 화이트' => 'White',
                '라군블루' => 'Blue',
                '타이푼실버' => 'Silver',
                '페퍼그레이' => 'Gray',
                '브라이트 실버' => 'Silver',
                '오션뷰' => 'Blue',
                '다크그래이색' => 'Gray',
                '아이언그레이' => 'Gray',
                '어비스블랙' => 'Black',
                '미드나잇블랙' => 'Black',
            ],
        ],
    ];

    /** @return array<string, string> */
    public static function normalizationMap(string $field): array
    {
        return self::NORMALIZATION_MAPS[$field] ?? [];
    }

    /** @return array<string, array<string, string>> */
    public static function labelMaps(string $locale = 'ru'): array
    {
        $locale = mb_strtolower(trim($locale), 'UTF-8');
        return self::LABELS[$locale] ?? [];
    }

    /** @return array<string, string> */
    public static function labelMap(string $field, string $locale = 'ru'): array
    {
        $all = self::labelMaps($locale);
        return $all[$field] ?? [];
    }
}
