<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Import catalog_model_trims from a JSON seed file generated by classify_trims.py.
 *
 * Usage:
 *   php artisan catalog:import-trims-seed
 *   php artisan catalog:import-trims-seed --file=/var/www/analysis/catalog_model_trims_seed.json
 *   php artisan catalog:import-trims-seed --file=... --apply
 */
class CatalogImportTrimsSeed extends Command
{
    protected $signature = 'catalog:import-trims-seed
        {--file=          : Path to seed JSON (default: /var/www/analysis/catalog_model_trims_seed.json)}
        {--apply          : Persist to DB (default: dry-run)}
        {--fresh          : Truncate catalog_model_trims before import}
        {--source=encar   : Filter records by source}';

    protected $description = 'Import catalog_model_trims from classify_trims.py output JSON';

    public function handle(): int
    {
        $file   = $this->option('file') ?: '/var/www/analysis/catalog_model_trims_seed.json';
        $apply  = (bool) $this->option('apply');
        $fresh  = (bool) $this->option('fresh');
        $source = (string) $this->option('source');

        $mode = $apply ? 'APPLY' : 'DRY-RUN';
        $this->info("catalog:import-trims-seed  mode={$mode}  file={$file}");
        $this->line('');

        if (! file_exists($file)) {
            $this->error("File not found: {$file}");
            return self::FAILURE;
        }

        $records = json_decode(file_get_contents($file), true);
        if (! is_array($records)) {
            $this->error('Invalid JSON');
            return self::FAILURE;
        }

        // Filter by source if needed
        if ($source) {
            $records = array_filter($records, fn($r) => ($r['source'] ?? '') === $source);
        }

        $this->line("Records in file : " . count($records));

        // Stats
        $byClass = [];
        foreach ($records as $r) {
            $c = $r['classification'] ?? '?';
            $byClass[$c] = ($byClass[$c] ?? 0) + 1;
        }
        foreach ($byClass as $cls => $cnt) {
            $this->line("  {$cls}: {$cnt}");
        }
        $this->line('');

        if ($apply && $fresh) {
            $this->warn('Truncating catalog_model_trims...');
            DB::table('catalog_model_trims')->truncate();
        }

        $inserted  = 0;
        $updated   = 0;
        $skipped   = 0;
        $chunkSize = 500;

        $chunks = array_chunk(array_values($records), $chunkSize);

        foreach ($chunks as $chunk) {
            $rows = [];
            foreach ($chunk as $r) {
                // Skip records with no useful trim information
                if (empty($r['trim_kr']) && empty($r['unknown_trim_part'])) {
                    $skipped++;
                    continue;
                }

                $rows[] = [
                    'source'            => $r['source']            ?? 'encar',
                    'make_kr'           => $r['make_kr']           ?? '',
                    'model_group_kr'    => $r['model_group_kr']    ?? '',
                    'badge_exact'       => $r['badge_exact']       ?? null,
                    'badge_group_exact' => $r['badge_group_exact'] ?? null,
                    'trim_kr'           => $r['trim_kr']           ?? null,
                    'trim_en'           => $r['trim_en']           ?? null,
                    'unknown_trim_part' => $r['unknown_trim_part'] ?? null,
                    'origin'            => $r['origin']            ?? 'inav',
                    'confidence'        => $r['confidence']        ?? 0.85,
                    'is_active'         => 1,
                    'notes'             => $r['classification']    ?? null,
                    'created_at'        => now(),
                    'updated_at'        => now(),
                ];
            }

            if (empty($rows)) {
                continue;
            }

            if ($apply) {
                // Upsert: on duplicate key update confidence + notes
                DB::table('catalog_model_trims')->upsert(
                    $rows,
                    ['source', 'make_kr', 'model_group_kr', 'badge_exact', 'badge_group_exact', 'trim_kr'],
                    ['trim_en', 'unknown_trim_part', 'confidence', 'notes', 'updated_at']
                );
                $inserted += count($rows);
            } else {
                $inserted += count($rows);
            }
        }

        $this->line("Would insert/update : {$inserted}");
        $this->line("Skipped (no trim)   : {$skipped}");

        if (! $apply) {
            $this->comment('Dry-run — pass --apply to persist.');
        } else {
            $this->info('Done.');
        }

        return self::SUCCESS;
    }
}
