<?php

namespace App\Dto;

readonly class LotDTO
{
    public function __construct(
        public string  $id,
        public string  $source,
        public string  $sourceName,
        public string  $make,
        public string  $model,
        public int     $year,
        public int     $price,
        public int     $mileage,
        public string  $location,
        public string  $lotUrl,
        public ?string $imageUrl,
        public ?string $vin,
        public ?string $auctionDate,
        public string  $createdAt,
        public ?string $makeEn          = null,
        public ?string $modelEn         = null,
        public ?string $generation      = null,
        public ?string $transmission    = null,
        public ?string $fuel            = null,
        public ?string $bodyType        = null,
        public ?string $driveType       = null,
        public ?string $color           = null,
        public ?float  $engineVolume    = null,
        public ?int    $retailValue     = null,
        public ?int    $repairCost      = null,
        public ?string $trim            = null,
        public ?string $trimEn         = null,
        public ?bool   $hasAccident         = null,
        public ?bool   $floodHistory        = null,
        public ?bool   $totalLossHistory    = null,
        public ?int    $ownersCount         = null,
        public ?string $plateNumber         = null,
        public ?array  $paidOptions          = null,
        public ?array  $options              = null,
        public ?string $lienStatus          = null,
        public ?string $seizureStatus       = null,
        public ?string $sellType            = null,
        public ?string $sellTypeRaw         = null,
        public ?int    $registrationYearMonth = null,
        public ?int    $insuranceCount      = null,
        public ?string $seatColor           = null,
        public ?int    $seatCount           = null,
        public ?string $firstRegDate        = null,
        public ?string $listedAt             = null,
    ) {}

    public function toArray(): array
    {
        return [
            'id'          => $this->id,
            'source'      => $this->source,
            'sourceName'  => $this->sourceName,
            'make'        => $this->make,
            'makeEn'      => $this->makeEn,
            'model'       => $this->model,
            'modelEn'     => $this->modelEn,
            'generation'  => $this->generation,
            'year'        => $this->year,
            'price'       => $this->price,
            'mileage'     => $this->mileage,
            'location'    => $this->location,
            'lotUrl'      => $this->lotUrl,
            'imageUrl'    => $this->imageUrl,
            'vin'         => $this->vin,
            'auctionDate'     => $this->auctionDate,
            'createdAt'       => $this->createdAt,
            'transmission'    => $this->transmission,
            'fuel'            => $this->fuel,
            'bodyType'        => $this->bodyType,
            'driveType'       => $this->driveType,
            'color'           => $this->color,
            'engineVolume'    => $this->engineVolume,
            'retailValue'     => $this->retailValue,
            'repairCost'      => $this->repairCost,
            'trim'            => $this->trim,
            'trimEn'          => $this->trimEn,
            'hasAccident'      => $this->hasAccident,
            'floodHistory'     => $this->floodHistory,
            'totalLossHistory' => $this->totalLossHistory,
            'ownersCount'      => $this->ownersCount,
            'plateNumber'      => $this->plateNumber,
            'paidOptions'      => $this->paidOptions,
            'options'          => $this->options,
            'lienStatus'       => $this->lienStatus,
            'seizureStatus'    => $this->seizureStatus,
            'sellType'         => $this->sellType,
            'sellTypeRaw'      => $this->sellTypeRaw,
            'registrationYearMonth' => $this->registrationYearMonth,
            'insuranceCount'   => $this->insuranceCount,
            'seatColor'        => $this->seatColor,
            'seatCount'        => $this->seatCount,
            'firstRegDate'     => $this->firstRegDate,
            'listedAt'         => $this->listedAt,
        ];
    }
}
