<?php

namespace App\Dto;

readonly class LotDTO
{
    public function __construct(
        public string  $id,
        public string  $source,
        public string  $sourceName,
        public string  $make,
        public string  $model,
        public int     $year,
        public int     $price,
        public int     $mileage,
        public ?string $damage,
        public string  $title,
        public string  $location,
        public string  $lotUrl,
        public ?string $imageUrl,
        public ?string $vin,
        public ?string $auctionDate,
        public string  $createdAt,
        public ?string $transmission    = null,
        public ?string $fuel            = null,
        public ?string $bodyType        = null,
        public ?string $driveType       = null,
        public ?string $color           = null,
        public ?float  $engineVolume    = null,
        public ?float  $fuelEconomy     = null,
        public ?int    $cylinders       = null,
        public ?string $secondaryDamage = null,
        public ?int    $retailValue     = null,
        public ?int    $repairCost      = null,
        public ?string $trim            = null,
        public ?bool   $hasAccident         = null,
        public ?bool   $floodHistory        = null,
        public ?bool   $totalLossHistory    = null,
        public ?int    $ownersCount         = null,
        public ?string $plateNumber         = null,
        public ?string $dealerName          = null,
        public ?string $dealerPhone         = null,
        public ?string $warrantyText         = null,
        public ?array  $paidOptions          = null,
        public ?string $lienStatus          = null,
        public ?string $seizureStatus       = null,
        public ?bool   $taxPaid             = null,
        public ?string $mileageGrade        = null,
        public ?int    $newCarPriceRatio    = null,
        public ?string $sellType            = null,
        public ?string $sellTypeRaw         = null,
        public ?int    $registrationYearMonth = null,
        public ?int    $insuranceCount      = null,
        public ?string $seatColor           = null,
        public ?int    $seatCount           = null,
        public ?bool   $isDomestic          = null,
        public ?string $importType          = null,
        public ?string $dealerCompany       = null,
        public ?string $dealerLocation      = null,
        public ?string $dealerDescription   = null,
        public ?string $registrationDate    = null,
    ) {}

    public function toArray(): array
    {
        return [
            'id'          => $this->id,
            'source'      => $this->source,
            'sourceName'  => $this->sourceName,
            'make'        => $this->make,
            'model'       => $this->model,
            'year'        => $this->year,
            'price'       => $this->price,
            'mileage'     => $this->mileage,
            'damage'      => $this->damage,
            'title'       => $this->title,
            'location'    => $this->location,
            'lotUrl'      => $this->lotUrl,
            'imageUrl'    => $this->imageUrl,
            'vin'         => $this->vin,
            'auctionDate'     => $this->auctionDate,
            'createdAt'       => $this->createdAt,
            'transmission'    => $this->transmission,
            'fuel'            => $this->fuel,
            'bodyType'        => $this->bodyType,
            'driveType'       => $this->driveType,
            'color'           => $this->color,
            'engineVolume'    => $this->engineVolume,
            'fuelEconomy'     => $this->fuelEconomy,
            'cylinders'       => $this->cylinders,
            'secondaryDamage' => $this->secondaryDamage,
            'retailValue'     => $this->retailValue,
            'repairCost'      => $this->repairCost,
            'trim'            => $this->trim,
            'hasAccident'      => $this->hasAccident,
            'floodHistory'     => $this->floodHistory,
            'totalLossHistory' => $this->totalLossHistory,
            'ownersCount'      => $this->ownersCount,
            'plateNumber'      => $this->plateNumber,
            'dealerName'       => $this->dealerName,
            'dealerPhone'      => $this->dealerPhone,
            'warrantyText'     => $this->warrantyText,
            'paidOptions'      => $this->paidOptions,
            'lienStatus'       => $this->lienStatus,
            'seizureStatus'    => $this->seizureStatus,
            'taxPaid'          => $this->taxPaid,
            'mileageGrade'     => $this->mileageGrade,
            'newCarPriceRatio' => $this->newCarPriceRatio,
            'sellType'         => $this->sellType,
            'sellTypeRaw'      => $this->sellTypeRaw,
            'registrationYearMonth' => $this->registrationYearMonth,
            'insuranceCount'   => $this->insuranceCount,
            'seatColor'        => $this->seatColor,
            'seatCount'        => $this->seatCount,
            'isDomestic'       => $this->isDomestic,
            'importType'       => $this->importType,
            'dealerCompany'    => $this->dealerCompany,
            'dealerLocation'   => $this->dealerLocation,
            'dealerDescription' => $this->dealerDescription,
            'registrationDate' => $this->registrationDate,
        ];
    }
}
